# Generated by Django 2.1.4 on 2019-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sd', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('cf', models.CharField(max_length=255)),
                ('ff', models.CharField(max_length=255)),
                ('pf', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
            ],
        ),
    ]
