# Generated by Django 2.1.1 on 2019-01-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sd', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('cf', models.CharField(max_length=255)),
                ('ff', models.CharField(max_length=255)),
                ('pf', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tamagotchi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('TDEE', models.IntegerField(default=0)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately_Active'), ('Very Active', 'Very Active')], default='Moderately Active', max_length=200)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'MALE')], default='Female', max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
