# Generated by Django 2.1.1 on 2019-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=257),
        ),
        migrations.AlterField(
            model_name='tamagotchi',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately_Active'), ('Very Active', 'Very Active')], default='Moderately Active', max_length=201),
        ),
    ]
